# Generated by Django 4.2.5 on 2024-09-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
